# Generated by Django 4.0.5 on 2022-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategory_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Код подкатегории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Название подкатегории'),
            preserve_default=False,
        ),
    ]
