# Generated by Django 4.0.5 on 2022-06-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_item_subcategory_code_item_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Код категорії'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код подкатегории'),
        ),
    ]
