# Generated by Django 4.0.5 on 2022-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0003_alter_item_category_code_alter_item_subcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_code',
            field=models.CharField(default=1, max_length=30, verbose_name='Код категорії'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Код подкатегории'),
        ),
    ]
