# Generated by Django 4.0.5 on 2022-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0004_alter_item_category_code_alter_item_subcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Опис відео(про що відоео)'),
        ),
    ]
