# Generated by Django 4.0.5 on 2022-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0005_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано(так|ні)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Код підкатегорії'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_name',
            field=models.CharField(max_length=30, verbose_name='Назва підкатегорії'),
        ),
    ]
