# Generated by Django 4.0.5 on 2022-07-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0008_remove_item_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категоря',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usersmanage.category', verbose_name='Назва категорії'),
        ),
    ]
