# Generated by Django 4.0.5 on 2022-07-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0009_category_alter_item_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Назва підкатегорії')),
            ],
            options={
                'verbose_name': 'Підкаатегоря',
                'verbose_name_plural': 'Підатегорії',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usersmanage.subcategory', verbose_name='Назва підкатегорії'),
        ),
    ]
